<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
    <head>
        <?php if ($this->mobile): ?>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <?php endif;?>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <?php
        $this->headTitle($this->title);
        $this->headTitle()->setSeparator(' - ');
        echo $this->headTitle($this->settings['site-name']);
        ?>

        <?php
        if (! $this->mobile) {
            $this->headLink()->appendStylesheet('yui/grids/grids-min.css');
        }

        $this->headLink()->appendStylesheet('css/minion.css');

        echo $this->headLink();
        ?>

        <?php
        $dependencies = array(
            'yui/yahoo-dom-event/yahoo-dom-event.js',
            'yui/selector/selector-min.js',
            'yui/connection/connection-min.js',
            'yui/datasource/datasource-min.js',
            'yui/animation/animation-min.js',
            'yui/json/json-min.js',
            'js/widget/help.js',
            'js/widget/message.js'
        );

        krsort($dependencies);

        foreach ($dependencies as $js) {
            $this->headScript()->prependFile($js);
        }
        ?>

        <?php echo $this->headScript();?>
    </head>
    <body class="<?php if ($this->mobile) : echo 'minion-mobile'; endif;?>">
        <div id="minion-top-bar">
            <a href="index.php"><?php echo $this->escape($this->settings['site-name']);?></a>

            <?php if ($this->user): ?>
            <ul id="minion-global-toolbar">
                <li id="minion-user"><a href="account.php"><?php echo $this->escape($this->user->getFullName());?></a></li>
                <li id="minion-settings"><a href="settings.php">Settings</a></li>
            </ul>
            <?php endif;?>
        </div>
