#!/usr/bin/env php
<?php

set_include_path(
    dirname(__FILE__) . '/library' 
  . PATH_SEPARATOR 
  . get_include_path()
);

require_once 'Zend/Loader/Autoloader.php';
$autoloader = Zend_Loader_Autoloader::getInstance();
$autoloader->registerNamespace('Minion_');

$client = new Minion_Client_Console();
