<?php
$this->headScript()->appendFile('js/minion.js')
                   ->appendFile('js/server-status-panel.js')
                   ->appendFile('js/search.js')
                   ->appendFile('js/domain-panel.js')
                   ->appendFile('js/server-nav.js');
?>
<div class="yui-gf">
    <div id="minion-navigation-container" class="yui-u first">
        <div id="minion-search">

        </div>
    </div>
    <div class="yui-u">
        <div id="minion-toolbar">
            
        </div>
        <div id="minion-content">
        </div>
    </div>
</div>

<script type="text/javascript">
    var manager = new MINION.manager(
        YAHOO.util.Dom.get('minion-content'),
        YAHOO.util.Dom.get('minion-navigation-container'),
        YAHOO.util.Dom.get('minion-search'),
        YAHOO.util.Dom.get('minion-toolbar'),
        <?php echo $this->mobile ? 'true' : 'false';?>,
        <?php echo json_encode($this->domains, true);?>
    );
</script>
