<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
    <head>
        <?php if ($this->mobile): ?>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <?php endif;?>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <?php
        $this->headTitle($this->title);
        $this->headTitle()->setSeparator(' - ');
        echo $this->headTitle('Minion');
        ?>

        <?php
        if (! $this->mobile) {
            $this->headLink()->appendStylesheet('yui/grids/grids-min.css');
        }

        $this->headLink()->appendStylesheet('css/minion.css');

        echo $this->headLink();
        ?>

        <?php echo $this->headScript();?>
    </head>
    <body class="<?php if ($this->mobile) : echo 'minion-mobile'; endif;?>">
        <?php echo $this->layout()->content ?>

        <div id="minion-copyright">
            Minion &bull; Simple web application monitoring &bull; New BSD license &bull; &copy;2009-<?php echo date('Y');?> Brad Griffith
        </div>
    </body>
</html>
