<div class="minion-login-container">
    <form action="login.php" method="post">
        <div class="minion-form-field">
            <label for="username">Username</label>
            <div class="minion-form-field-contents">
                <input type="text" id="username" name="username" class="minion-input-medium" />
            </div>
        </div>
        <div class="minion-form-field">
            <label for="password">Password</label>
            <div class="minion-form-field-contents">
                <input type="password" id="password" name="password" class="minion-input-medium" />
            </div>
        </div>
        <div class="minion-login-form-footer">
            <a class="minion-button">Sign in</a>
        </div>
        <div class="minion-login-help">
            <a href="#">I forgot my username or password</a>
        </div>
    </form>
</div>
