<?php echo $this->settingsNav('settings-notifications');?>

<div id="minion-settings-container">
    <label>Email notifications</label>
    <div class="minion-form-field-note">
        Provide connection details for one or more mail transports for sending
        email notifications via Minion.  When sending messages, Minion will
        attempt to use the default transport first and then fall back to any
        others configured, if the default does not work.
    </div>
    <br />
    <div class="minion-settings-listing-toolbar">
        <ul>
            <li><a class="minion-settings-add" href="settings-notification-email-transport.php">Add Transport</a></li>
            <li><a class="minion-settings-default" href="settings-notification-email-transport-default.php">Change Default</a></li>
        </ul>
        <div class="minion-clear">&nbsp;</div>
    </div>
    <table class="minion-settings-listing" cellspacing="0">
        <tbody>
            <tr>
                <td>
                    Sendmail
                    <div class="minion-settings-info">
                        Uses the default PHP mail() function to send messages.    
                    </div>
                </td>
                <td class="minion-settings-info minion-center">
                    <div class="minion-settings-default">Default</div>
                </td>
                <td class="minion-settings-actions">
                    <a class="minion-settings-test-message" href="settings-notification-email-transport-test.php">Send a Test Message</a>
                    <a class="minion-settings-edit" href="settings-notification-email-transport-edit.php">Edit</a>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="minion-settings-listing-footer">&nbsp;</div>

    <br />
    <br />

    <label>Other notifications</label>
    <div class="minion-form-field-note">
        Sometimes its helpful to have a secondary notification method.  Email
        might not be effective enough at communicating an urgent message, or perhaps
        another method is just useful as a backup.  Setup text messaging and social
        network messaging below.
    </div>

    <br />
    <br />

    <label>SMS email gateways</label>
    <a id="minion-help-sms-gateways" class="minion-help-link" href="#">Help</a>
    <div class="minion-form-field-note">
        Minion uses email gateways to send text messages.  Email gateways are 
        special email domains provided by cell phone carriers that, along with
        the customer's phone number, allow the send of an SMS over email.  If your
        cell carrier's gateway isn't already entered, configure it here.
    </div>

</div>
