<?php echo $this->settingsNav('settings-users');?>

<div id="minion-settings-container">
    <div class="yui-g">
        <div class="yui-u first">
            <label>Inviting new users</label>
            <div class="minion-form-field-note">
                They'll get an email and then choose a username and password.
            </div>
        </div>
        <div class="yui-u">
            <label>Sheduling vacation</label>
            <div class="minion-form-field-note">
                Stops notifications to a user on vacation and allows substituting
                a different user to receive them.
            </div>
        </div>
    </div>
    <br />
    <div class="minion-settings-listing-toolbar">
        <ul>
            <li><a class="minion-settings-add" href="settings-users-edit.php">Add User</a></li>
        </ul>
        <div class="minion-clear">&nbsp;</div>
    </div>
    <table class="minion-settings-listing" cellspacing="0">
        <tbody>
            <tr>
                <td>
                    Brad Griffith &lt;griffbrad@gmail.com&gt;<br />
                    <div class="minion-settings-info">
                        Delta Systems<br />
                        System Administrator
                    </div>
                </td>
                <td class="minion-settings-info">
                    <span>Cell</span> 573-356-8671<br />
                    <span>Office</span> 573-442-9855 x207<br />
                    <span>Google Talk</span> griffbrad
                </td>
                <td class="minion-settings-actions">
                    <a class="minion-settings-password" href="settings-user-password.php?user-id=1">Change Password</a>
                    <a class="minion-settings-vacation" href="settings-user-vacation.php?user-id=1">Schedule Vacation</a>
                    <a class="minion-settings-edit" href="settings-user-edit.php?user-id=1">Edit</a>
                </td>
            </tr>
        </tbody> 
    </table>
    <div class="minion-settings-listing-footer">&nbsp;</div>
</div>
