<ul id="minion-settings-navigation">
    <li class="selected"><a href="settings.php">General</a></li>
    <li><a href="settings/notifications.php">Notifications</a></li>
    <li><a href="settings/users.php">Users</a></li>
    <li><a href="settings/tasks.php">Tasks</a></li>
    <li><a href="settings/servers.php">Servers</a></li>
</ul>

<div id="minion-settings-container">
    <form id="minion-form-settings" action="settings.php" method="post">
        <?php $this->formHandler()->display(); ?> 

        <div class="minion-form-footer">
            <a id="minion-form-submit" class="minion-button">Save Settings</a>
        </div>
    </form>
</div>

<div id="date-help-body" class="minion-hidden">
    Specify the format you'd like to use when displaying dates with the template
    tags listed below.  For example, enter "%b %e, %Y, %R" for the following format:
    <?php echo strftime('%b, %e, %Y, %R');?>.

    <div class="yui-g">
        <div class="yui-u first">
            <dl>
                <dt>%a</dt>
                <dd>Abbreviated weekday name</dd>

                <dt>%b</dt>
                <dd>Abbreviated month name</dd>
                
                <dt>%c</dt>
                <dd>Standard for current locale</dd>
                
                <dt>%R</dt>
                <dd>Full time on 24-hour clock</dd>

                <dt>%k</dt>
                <dd>Hour on 24-hour clock</dd>
                
                <dt>%M</dt>
                <dd>Minutes</dd>

                <dt>%p</dt>
                <dd>AM or PM</dd>

                <dt>%y</dt>
                <dd>Year without the century</dd>

                <dt>%x</dt>
                <dd>Standard format without time</dd>
            </dl>
        </div>
        <div class="yui-u">
            <dl>
                <dt>%A</dt>
                <dd>Full weekday name</dd>
                
                <dt>%B</dt>
                <dd>Full month name</dd>

                <dt>%e</dt>
                <dd>Day of month as number</dd>

                <dt>%r</dt>
                <dd>Full time on 12-hour clock</dd>

                <dt>%l</dt>
                <dd>Hour on 12-hour clock</dd>

                <dt>%S</dt>
                <dd>Seconds</dd>

                <dt>%P</dt>
                <dd>Like %p, but lower-case</dd>

                <dt>%Y</dt>
                <dd>Full year</dd>
                
                <dt>%X</dt>
                <dd>Standard format without date</dd>
            </dl>
        </div>

        <a target="_blank" class="minion-external" href="http://www.php.net/strftime">Learn more at php.net</a>
    </div>
</div>

<script type="text/javascript">
    var dateHelpLinks = [
        YAHOO.util.Dom.get('minion-help-desktop-date'),
        YAHOO.util.Dom.get('minion-help-mobile-date')
    ]; 

    for (var i = 0; i < dateHelpLinks.length; i++) {
        var link = dateHelpLinks[i];

        YAHOO.util.Event.on(link, 'click', function(e) {
            YAHOO.util.Event.preventDefault(e);

            var help = new MINION.widget.Help();

            help.setHeader('Date formatting')
                .setBody(YAHOO.util.Dom.get('date-help-body').innerHTML)
                .render();
        });
    }

    var submit = YAHOO.util.Dom.get('minion-form-submit');

    YAHOO.util.Event.on(submit, 'click', function(e) {
        YAHOO.util.Event.preventDefault(e);
        
        YAHOO.util.Dom.get('minion-form-settings').submit();
    });
</script>
